# Generated by Django 5.1.1 on 2025-02-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_user_school_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='school_code',
        ),
        migrations.AddField(
            model_name='user',
            name='school_code',
            field=models.ManyToManyField(blank=True, to='backend.school', verbose_name='École actuelle'),
        ),
    ]
