# Generated by Django 5.1.1 on 2025-02-12 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_user_school_code_user_school_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentregistration',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='school_year',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teacherregistration',
            name='school',
        ),
        migrations.RemoveField(
            model_name='teacherregistration',
            name='teacher',
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('student', 'Élève'), ('teacher', 'Enseignant'), ('parent', 'Parent')], max_length=10, verbose_name='Rôle')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Payé')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_graduated', models.BooleanField(default=False, verbose_name='Élève admis(e)')),
                ('is_transferred', models.BooleanField(default=False, verbose_name='Élève transféré(e)')),
                ('is_suspended', models.BooleanField(default=False, verbose_name='Élève suspendu(e)')),
                ('is_withdrawn', models.BooleanField(default=False, verbose_name='Élève retiré(e)')),
                ('is_reinscribed', models.BooleanField(default=False, verbose_name='Élève réinscrit(e)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('children', models.ManyToManyField(blank=True, related_name='registered_parents', to=settings.AUTH_USER_MODEL, verbose_name='Enfants')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.classroom', verbose_name='Salle de classe')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.school', verbose_name='École')),
                ('school_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.schoolyear', verbose_name='Année scolaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Inscription utilisateur',
                'verbose_name_plural': 'Inscriptions utilisateurs',
                'unique_together': {('user', 'role', 'school_year', 'classroom')},
            },
        ),
        migrations.AlterField(
            model_name='studentevaluation',
            name='inscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userregistration', verbose_name='Inscription'),
        ),
        migrations.DeleteModel(
            name='ParentRegistration',
        ),
        migrations.DeleteModel(
            name='TeacherRegistration',
        ),
        migrations.DeleteModel(
            name='StudentRegistration',
        ),
    ]
