# Generated by Django 5.1.1 on 2024-09-20 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_userrole_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levelscolaship',
            options={'verbose_name': 'Niveau scolaire', 'verbose_name_plural': 'Niveaux scolaires'},
        ),
        migrations.AlterModelOptions(
            name='schoolcycle',
            options={'verbose_name': 'Cycle scolaire', 'verbose_name_plural': 'Cycles scolaires'},
        ),
        migrations.AlterModelOptions(
            name='schoolseries',
            options={'verbose_name': 'Série', 'verbose_name_plural': 'Séries'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
    ]
