# Generated by Django 5.1.1 on 2025-02-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_studentregistration_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='school_code',
        ),
    ]
