# Generated by Django 5.1.1 on 2025-02-12 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_user_school_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userregistration',
            unique_together={('user', 'school_year', 'classroom')},
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='role',
        ),
    ]
