# Generated by Django 5.1.1 on 2024-09-20 12:56

import backend.models.school_manager.school_manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_levelscolaship_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('code', backend.models.school_manager.school_manager.UUID4Field(auto_created=True, editable=False, max_length=17, unique=True)),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name="Nom d'école")),
                ('address', models.CharField(max_length=200, verbose_name='Adresse')),
                ('city', models.CharField(choices=[('Brazzaville', 'Brazzaville'), ('Pointe Noire', 'Pointe Noire')], max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Code postal')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'École',
                'verbose_name_plural': 'Écoles',
            },
        ),
    ]
