# Generated by Django 5.1.1 on 2024-09-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_school_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'Rôle', 'verbose_name_plural': 'Rôles'},
        ),
    ]
