# Generated by Django 5.1.1 on 2024-09-20 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_userrole_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.school', verbose_name='Code École'),
        ),
        migrations.CreateModel(
            name='StaffProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom')),
                ('firstname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Prénom')),
                ('gender', models.CharField(blank=True, choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=10, null=True, verbose_name='Sexe')),
                ('nationality', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nationalité')),
                ('birthplace', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu de naissance')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/', verbose_name='Photo')),
                ('skype', models.CharField(blank=True, max_length=50, null=True, verbose_name='Skype')),
                ('gmail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Gmail')),
                ('discord', models.URLField(blank=True, null=True, verbose_name='Discord')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Profil de l'utilisateur",
                'verbose_name_plural': "Profils de l'utilisateurs",
            },
        ),
    ]
