# Generated by Django 5.1.1 on 2024-09-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_parentofstudent_pupil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
