# Generated by Django 5.1.1 on 2024-09-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_schoolyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='year',
            field=models.CharField(max_length=20, verbose_name='Année scolaire'),
        ),
    ]
