# Generated by Django 5.1.1 on 2024-09-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_schoolyear_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyear',
            name='is_current_year',
            field=models.BooleanField(default=False, verbose_name='Année en cours'),
        ),
    ]
