# Generated by Django 5.1.1 on 2024-09-20 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_rename_levelscolaship_schoollevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la salle')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.school', verbose_name='École')),
                ('school_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.schoollevel', verbose_name='Niveau scolaire')),
            ],
            options={
                'verbose_name': 'Salle de classe',
                'verbose_name_plural': 'Salles de classes',
            },
        ),
    ]
