# Generated by Django 5.1.1 on 2024-09-20 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nom du type de document')),
            ],
            options={
                'verbose_name': 'Type de document',
                'verbose_name_plural': 'Types de documents',
            },
        ),
        migrations.CreateModel(
            name='SanctionOrAppreciationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name="Nom du type de sanction ou d'appréciation")),
            ],
            options={
                'verbose_name': "Type de sanction ou d'appréciation",
                'verbose_name_plural': "Types de sanctions ou d'appréciations",
            },
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nom du groupe de matière')),
            ],
            options={
                'verbose_name': 'Groupe de matière',
                'verbose_name_plural': 'Groupes de matières',
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('is_paid', models.BooleanField(default=False, verbose_name='Payé')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_graduated', models.BooleanField(default=False, verbose_name='Élève admise')),
                ('is_transferred', models.BooleanField(default=False, verbose_name='Élève transféré(e)')),
                ('is_suspended', models.BooleanField(default=False, verbose_name='Élève suspendu(e)')),
                ('is_withdrawn', models.BooleanField(default=False, verbose_name='Élève retiré(e)')),
                ('is_reinscribed', models.BooleanField(default=False, verbose_name='Élève réinscrit(e)')),
                ('is_inscribed', models.BooleanField(default=False, verbose_name='Élève réinscrit(e)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.classroom', verbose_name='Salle de classe')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.schoolyear', verbose_name='Année scolaire')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.pupil', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
            },
        ),
    ]
