# Generated by Django 5.1.1 on 2024-09-22 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_teacherschool'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('student', 'classroom', 'school_year')},
        ),
        migrations.AddField(
            model_name='teacherschool',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date de début d'emploi"),
        ),
        migrations.AddField(
            model_name='teacherschool',
            name='phone_work',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone professionnel'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='is_graduated',
            field=models.BooleanField(default=False, verbose_name='Élève admis(e)'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nom de la matière')),
                ('coefficient', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subjectgroup', verbose_name='Groupe de matière')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.school', verbose_name='École')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['name'],
                'unique_together': {('name', 'group')},
            },
        ),
        migrations.AddField(
            model_name='teacherschool',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='backend.subject', verbose_name='Matières enseignées'),
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='is_inscribed',
        ),
        migrations.CreateModel(
            name='SchoolCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('events', models.TextField(verbose_name='Événements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.school', verbose_name='École')),
            ],
            options={
                'verbose_name': 'Calendrier scolaire',
                'verbose_name_plural': 'Calendriers scolaires',
                'ordering': ['-date'],
                'unique_together': {('date', 'school')},
            },
        ),
        migrations.CreateModel(
            name='SchoolHoliday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.school', verbose_name='École')),
            ],
            options={
                'verbose_name': 'Congé scolaire',
                'verbose_name_plural': 'Congés scolaires',
                'ordering': ['-date'],
                'unique_together': {('date', 'school')},
            },
        ),
        migrations.CreateModel(
            name='StudentEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('evaluation_date', models.DateField(verbose_name="Date de l'évaluation")),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Score')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.inscription', verbose_name='Inscription')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.schoolyear', verbose_name='Année scolaire')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.pupil', verbose_name='Élève')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subject', verbose_name='Matière')),
            ],
            options={
                'verbose_name': "Évaluation d'élève",
                'verbose_name_plural': "Évaluations d'élèves",
                'unique_together': {('student', 'subject', 'evaluation_date')},
            },
        ),
        migrations.CreateModel(
            name='SchoolSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=10, verbose_name='Jour')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.classroom', verbose_name='Salle de classe')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.school', verbose_name='École')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.teacherschool', verbose_name='Professeur')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subject', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Emplois du temps scolaire',
                'verbose_name_plural': 'Emplois du temps scolaires',
                'ordering': ['subject', 'day', 'start_time'],
                'unique_together': {('subject', 'day', 'start_time', 'classroom')},
            },
        ),
        migrations.CreateModel(
            name='SchoolProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.school', verbose_name='École')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subject', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Programme scolaire',
                'verbose_name_plural': 'Programmes scolaires',
                'ordering': ['subject'],
                'unique_together': {('subject', 'school')},
            },
        ),
    ]
