# Generated by Django 5.1.1 on 2024-09-25 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_tag_infomation_event_announcement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Infomation',
            new_name='Information',
        ),
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('cover_image', models.ImageField(upload_to='cover_images')),
                ('pdf_file', models.FileField(upload_to='pdf_files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.school')),
            ],
            options={
                'verbose_name': 'Ebook',
                'verbose_name_plural': 'Ebooks',
                'ordering': ['-created_at'],
            },
        ),
    ]
