# Generated by Django 5.1.1 on 2024-09-25 07:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_rename_infomation_information_ebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentofstudent',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='parentofstudent',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='parentofstudent',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='parentofstudent',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='teacherschool',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='teacherschool',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='teacherschool',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='teacherschool',
            name='twitter',
        ),
        migrations.AddField(
            model_name='parentofstudent',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, verbose_name='Liens sociaux'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, verbose_name='Liens sociaux'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, verbose_name='Liens sociaux'),
        ),
        migrations.AddField(
            model_name='teacherschool',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, verbose_name='Liens sociaux'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parentofstudent',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='teacherschool',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
