# Generated by Django 5.1.1 on 2024-09-28 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_rename_infomation_information_ebook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanctionorappreciationtype',
            options={'ordering': ['name'], 'verbose_name': "Type de sanction ou d'appréciation", 'verbose_name_plural': "Types de sanctions ou d'appréciations"},
        ),
        migrations.CreateModel(
            name='SchoolReportCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=5, verbose_name='Grade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.school', verbose_name='École')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.pupil', verbose_name='Élève')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subject', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Bulletin de notes',
                'verbose_name_plural': 'Bulletins de notes',
            },
        ),
    ]
