# Generated by Django 5.1.1 on 2024-10-04 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_alter_sanctionorappreciationtype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectAttribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.classroom', verbose_name='Salle de classe')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.schoolyear', verbose_name='Année scolaire')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subject', verbose_name='Matière')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.teacherschool', verbose_name='Professeur')),
            ],
            options={
                'verbose_name': 'Attribution de matière',
                'verbose_name_plural': 'Attributions de matières',
                'ordering': ['subject'],
                'unique_together': {('subject', 'classroom')},
            },
        ),
    ]
