# Generated by Django 5.1.1 on 2024-10-04 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_subjectattribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('is_read', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='SchoolAbsence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('justified', models.BooleanField(default=False)),
                ('absence_date', models.DateField(verbose_name="Date de l'absence")),
                ('absence_type', models.CharField(max_length=100, verbose_name="Type d'absence")),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.inscription', verbose_name='Inscription')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.schoolyear', verbose_name='Année scolaire')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.pupil', verbose_name='Élève')),
            ],
            options={
                'verbose_name': "Absence d'élève",
                'verbose_name_plural': "Absences d'élèves",
            },
        ),
    ]
