# Generated by Django 5.1.1 on 2024-10-04 15:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_message_schoolabsence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('payment_date', models.DateField(auto_now_add=True, verbose_name='Date de paiement')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Mode de paiement')),
                ('is_partial', models.BooleanField(default=False, verbose_name='Paiement partiel')),
                ('reference_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro de référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('Terminé', 'Terminé'), ('Annulé', 'Annulé')], default='En attente', max_length=20, verbose_name='Statut')),
                ('tracked_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de suivi')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='backend.payment')),
            ],
            options={
                'verbose_name': 'Suivi de paiement',
                'verbose_name_plural': 'Suivis de paiements',
                'ordering': ['-tracked_date'],
            },
        ),
        migrations.CreateModel(
            name='SchoolInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField(verbose_name='Date de facturation')),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('schooling_of', models.CharField(choices=[('Janvier', 'Janvier'), ('Février', 'Février'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Août', 'Août'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Décembre')], max_length=10)),
                ('invoice_status', models.CharField(choices=[('Entièrement payé', 'Entièrement payé'), ('Non payé', 'Non payé'), ('Avance', 'Avance')], max_length=20, verbose_name='Statut')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Mode de paiement')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Facture récurrente')),
                ('recurrence_period', models.CharField(blank=True, choices=[('Mensuel', 'Mensuel'), ('Trimestriel', 'Trimestriel'), ('Annuel', 'Annuel')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais de retard')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.classroom', verbose_name='Salle de classe')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='backend.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='backend.pupil')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='backend.schoolinvoice'),
        ),
    ]
