# Generated by Django 5.1.1 on 2024-10-04 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_payment_paymenttracking_schoolinvoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolabsence',
            name='inscription',
        ),
    ]
