# Generated by Django 5.1.1 on 2024-10-04 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_remove_schoolabsence_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolabsence',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.classroom', verbose_name='Salle de classe'),
        ),
    ]
