# Generated by Django 5.1.1 on 2024-10-05 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_alter_teacherschool_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinvoice',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='École', to='backend.school'),
        ),
        migrations.AlterField(
            model_name='schoolinvoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Élève', to='backend.pupil'),
        ),
    ]
