# Generated by Django 5.1.1 on 2024-10-05 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_alter_schoolinvoice_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du matériel')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('material_type', models.CharField(choices=[('livre', 'Livre'), ('ordinateur', 'Ordinateur'), ('fourniture', 'Fourniture scolaire'), ('autre', 'Autre')], max_length=50, verbose_name='Type de matériel')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
                ('available_quantity', models.PositiveIntegerField(verbose_name='Quantité disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.school')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True, verbose_name='Date de demande')),
                ('quantity_requested', models.PositiveIntegerField(verbose_name='Quantité demandée')),
                ('status', models.CharField(choices=[('approuvé', 'Approuvé'), ('rejeté', 'Rejeté'), ('en attente', 'En attente')], default='en attente', max_length=20, verbose_name='Statut')),
                ('approved_date', models.DateField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('rejected_reason', models.TextField(blank=True, null=True, verbose_name='Raison du rejet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='backend.schoolmaterial')),
            ],
            options={
                'verbose_name': 'Demande de matériel',
                'verbose_name_plural': 'Demandes de matériel',
            },
        ),
    ]
