# Generated by Django 5.1.1 on 2024-10-05 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_expensecategory_schoolexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.schoolcycle', verbose_name='Cycle scolaire'),
        ),
    ]
