# Generated by Django 5.1.1 on 2024-10-10 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_school_school_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentofstudent',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_school', to='backend.school', verbose_name='École'),
        ),
        migrations.AlterField(
            model_name='information',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
