# Generated by Django 5.1.1 on 2024-10-10 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_parentofstudent_school_alter_information_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentofstudent',
            name='school',
        ),
    ]
