# Generated by Django 5.1.1 on 2024-10-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_alter_announcement_school_alter_announcement_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
