# Generated by Django 5.1.1 on 2024-10-10 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_alter_announcement_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.school'),
        ),
    ]
