# Generated by Django 5.1.1 on 2024-10-10 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_alter_schoolmaterial_school_alter_subject_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolschedule',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.school', verbose_name='École'),
        ),
    ]
