# Generated by Django 5.1.1 on 2024-10-10 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_alter_schoolschedule_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinvoice',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='École', to='backend.school'),
        ),
    ]
