# Generated by Django 5.1.1 on 2024-10-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_alter_schoolinvoice_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinvoice',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Payé'),
        ),
    ]
