# Generated by Django 5.1.1 on 2024-10-10 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_schoolinvoice_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Payé'),
        ),
        migrations.AlterField(
            model_name='schoolinvoice',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='École', to='backend.school'),
        ),
    ]
