# Generated by Django 5.1.1 on 2024-10-10 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_payment_is_paid_alter_schoolinvoice_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolreportcard',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.school', verbose_name='École'),
        ),
    ]
